"""
Django settings for profile_manager project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os, pytz

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x7(-!h^^56!tru&eq_n%**kfb68q-7$a=ub(9)g5b^++l4k8ix'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userprofile',
    'oauth2client',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'profile_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'profile_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOCAL_TIME_ZONE = pytz.timezone('Asia/Calcutta')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'userprofile.UserProfile'

# Media conf

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


AUTHENTICATION_BACKENDS = [\
    'django.contrib.auth.backends.ModelBackend',
    'userprofile.backends.EmailBackend'
]

LOGIN_URL = 'uprofile:login'
LOGIN_REDIRECT_URL = 'uprofile:home'


# Gmail API Credentials

# OAuth2 Credentials
GOOGLE_OAUTH2_CLIENT_ID = '150492781827-52j6r8742u34c5kku82u6h7c81u39keu.apps.googleusercontent.com'
GOOGLE_OAUTH2_CLIENT_SECRET = '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'

# GMAIL_API_CREDENTIALS = {
#     # 'web': {
#     #     'client_id': 'YOUR_CLIENT_ID',
#     #     'client_secret': 'YOUR_CLIENT_SECRET',
#     #     'redirect_uris': ['YOUR_REDIRECT_URI'],
#     #     'auth_uri': 'https://accounts.google.com/o/oauth2/auth',
#     #     'token_uri': 'https://accounts.google.com/o/oauth2/token',
#     # }
#     'web': {
#         'client_id': '922521259398-ofsf7a844s6pr25a8mbdjehsen9b9rbu.apps.googleusercontent.com',
#         'client_secret': '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',
#         # 'redirect_uris': ["http://127.0.0.1:8000"],
#         'auth_uri': 'https://accounts.google.com/o/oauth2/auth',
#         'token_uri': 'https://oauth2.googleapis.com/token',
#     }
# }